### ISSUE TITLE
Problem with (global 'ESX')

### ISSUE THREAD

**Issue by BlackFlag00** [Xovos/esx_illegal#10]
Hi, I have an error with the drugs. this is the error code: I have alredy put all the items in my db

`@esx_illegal/client/coke.lua:141: attempt to index a nil value (global 'ESX')
> fn (esx_illegal/client/coke.lua;12)

![screen](https://user-images.githubusercontent.com/62483815/77235866-c0716480-6bb9-11ea-9847-1fabe1c934d2.PNG)

The error is the same for all the drugs file

**Comment by Xovos** [comment]
Did you install the esx framework?
because this is an extension.
[https://github.com/ESX-Org/es_extended](https://github.com/ESX-Org/es_extended)

**Comment by BlackFlag00** [comment]
yes, i have installed it

**Comment by bypeke** [comment]
Hi not work any drugs...

**Comment by Xovos** [comment]
Hi
I have no clue why this is happening.
@bypeke are you getting the same error?

**Comment by bypeke** [comment]
I have added everything in resources-esx
and the sql injected correctly. and once inside the game nothing comes out, it's like I don't recognize it.

**Comment by Xovos** [comment]
Does the console show that it started it?

**Comment by bypeke** [comment]
Yes, when enter in game and tp to coordenates nothing appears.

https://gyazo.com/e33c2ffd9cb4a88e0a06feed0a61c80a

**Comment by Xovos** [comment]
I fixed it in the latest update :)
