### ISSUE TITLE
Error with Client.lua and coke.lua

### ISSUE THREAD

**Issue by EPICxJustice** [Xovos/esx_illegal#11]
![Capture](https://user-images.githubusercontent.com/55562631/77565372-81cdf980-6e9a-11ea-85c2-95af90439588.PNG)

I do not know why i am getting this specific error, can someone help me please

**Comment by EPICxJustice** [comment]
Okay, i managed to fix the issues i was previously having. But there is no way to enter the money washing facilities and the drug houses? Help

**Comment by Xovos** [comment]
Use this script:
https://github.com/Xovos/XOVOS_Teleport

**Comment by EPICxJustice** [comment]
okay, another thing. sorry. But whenever i press E on the harvesting, it doesnt do anything. I press it, it removes the key prompt from the top left and just doesnt do anything.

**Comment by Xovos** [comment]
Are you getting an error in the console? f8

**Comment by EPICxJustice** [comment]
https://drive.google.com/file/d/1IvZupW48LlmaiyKXZjugfqhxkuyZp8SO/view?usp=sharing

No errors, its like it just stops working when i harvest

**Comment by Xovos** [comment]
Could you try coke for me or any other drug than i can know if it's just heroin?

**Comment by EPICxJustice** [comment]
yea it happens with weed too

**Comment by Xovos** [comment]
I'll look in to it

**Comment by EPICxJustice** [comment]
okay, just get back to me when you figure it out cause your script is kind of my main resource for drugs in my server lol

**Comment by Xovos** [comment]
Hi
I just loaded up the test server and it just works for me.
https://drive.google.com/file/d/115i1pw-lhSZKw40lRk7U_OHjmSTAE-0j/view?usp=sharing
Could you please remove the script completely and download it again also remove the items from your db and readd them and let me know if that fixes annyhing.

**Comment by EPICxJustice** [comment]
huh that is very strange i will try that, 1 second

**Comment by EPICxJustice** [comment]
Do i have to keep the folder title the same or can i change it to esx_illegal?

**Comment by Xovos** [comment]
You should always remove the "-master"

**Comment by EPICxJustice** [comment]
Do you know of any scripts that would interfere with yours?

**Comment by EPICxJustice** [comment]
okay, so the icons are fixed and everything is where it should be on the map. I reinstalled all of the items into the database and the script itself. There has to be another script interfering with it. Thats the only thing i can think of

**Comment by Xovos** [comment]
are you on the latest version of esx or are you on an old version (at least 6 months old)

**Comment by EPICxJustice** [comment]
ìm not sure, im using ZAP

**Comment by Xovos** [comment]
did you create your server recently or more than 6 months ago?

**Comment by EPICxJustice** [comment]
recently

**Comment by Xovos** [comment]
thats not it then hmm are you still expicinancing the same problem?

**Comment by EPICxJustice** [comment]
Yes, i had the regular esx_drugs installed but i removed it and restarted the server, but that wasnt it

**Comment by EPICxJustice** [comment]
Has anyone else experienced this problem before me?

**Comment by Xovos** [comment]
not that i know

**Comment by EPICxJustice** [comment]
huh this is very unfortunate

**Comment by EPICxJustice** [comment]
i would fresh reset all of my server but ive done too much in it

**Comment by EPICxJustice** [comment]
i want to use that as a last resort

**Comment by Xovos** [comment]
I haven't got a clue what the problem is and i don't even get any indication form the console, i'm sorry about this.

**Comment by EPICxJustice** [comment]
eh its fine, what scripts are in your server?

**Comment by Xovos** [comment]
a lot but it's very outdated these days

**Comment by EPICxJustice** [comment]
how long have you had your script installed in your server for?

**Comment by EPICxJustice** [comment]
can you send me the files that are in your server?

**Comment by EPICxJustice** [comment]
at this point, idk what it can be

**Comment by Xovos** [comment]
it has been installed for about 1.5 years now but it's running an older version of the script because the version of esx is very old.

**Comment by Xovos** [comment]
this won't work on a newer server.

**Comment by EPICxJustice** [comment]
can we try it? Worst case i install the new files and just overwrite the old ones

**Comment by EPICxJustice** [comment]
I dont know if it is because there is a script interfering with it or what. Just from looking at my scripts i dont think there are any

**Comment by EPICxJustice** [comment]
but im not sure

**Comment by Xovos** [comment]
[esx_illegal.zip](https://github.com/Xovos/esx_illegal/files/4384317/esx_illegal.zip)
Here you go

**Comment by EPICxJustice** [comment]
thanks, ill let you know what happens

**Comment by EPICxJustice** [comment]
is there a way to enable blips?

**Comment by Xovos** [comment]
It wasn't yet implemented but they should be at the same spot.

**Comment by EPICxJustice** [comment]
mmm theyre in your video. ill just make the blips for em

**Comment by Xovos** [comment]
The video was recorded on my test server with the latest version running on it.

**Comment by EPICxJustice** [comment]
got it, also the script works now. I havent tested the moneywash, also the processing.

**Comment by EPICxJustice** [comment]
harvesting does though

**Comment by Xovos** [comment]
So you are running an older version

**Comment by EPICxJustice** [comment]
yes

**Comment by EPICxJustice** [comment]
which seems to work, which is good

**Comment by Xovos** [comment]
Nice

**Comment by EPICxJustice** [comment]
![Capture](https://user-images.githubusercontent.com/55562631/77599578-8ebf0d00-6edb-11ea-9fdf-b004a51e51db.PNG)

Also should i have something in here?

**Comment by Xovos** [comment]
their is another script for those interiors i can't remember the name tough.

**Comment by EPICxJustice** [comment]
okay i mightve found it, anyways, thank you so much for the help. Honestly thought i wasnt gonna be able to use this amazing script. Glad we found a fix

**Comment by EPICxJustice** [comment]
Would you happen to know why peoples jobs dont save? Like ill give them the police job and they will have it until they leave and rejoin then i have to give it to them again. Thoughts?

**Comment by Xovos** [comment]
Hi
I changed the old version of the script so you can enable te blimps and everything:
[esx_illegal.zip](https://github.com/Xovos/esx_illegal/files/4386658/esx_illegal.zip)
about the jobs, that sounds like a database problem because when you change a job it shoud also be updated in the users table for that user.
Change your job and check if you user's job changed in the user table.

**Comment by EPICxJustice** [comment]
Okay, that’s great to hear. So I kinda of got impatient and made my own blips for the drugs lol. But with the jobs, it was just because the people weren’t using their police character. Thanks for the help on that too

**Comment by Xovos** [comment]
Np, happy to help.

**Comment by EPICxJustice** [comment]
I dont know if you would know, but since we're here, do you know how to add more car dealerships with esx_vehicleshop?

**Comment by Xovos** [comment]
no sorry
