### ISSUE TITLE
Script ERROR

### ISSUE THREAD

**Issue by mxtry** [Xovos/esx_illegal#12]
SCRIPT ERROR: @esx_illegal/server/heroin.lua:24: attempt to call a nil value (field 'canSwapItem')

**Comment by Xovos** [comment]
Hi

you are running an old verion of esx, please use the pre limit verion of this script.

[https://github.com/Xovos/esx_illegal/tree/pre-limit-update](https://github.com/Xovos/esx_illegal/tree/pre-limit-update)

**Comment by mxtry** [comment]
i am using the new one with weight instead of limit

**Comment by Xovos** [comment]
Hi

Strange, it can't find the new function that came with the limit update.
