### ISSUE TITLE
Server reported an error. Please help me!

### ISSUE THREAD

**Issue by movohou** [Xovos/esx_illegal#15]
Hello brother, thank you for your drug mission! I like it very much, but there's a problem you need to help solve, as follows: all drugs can't be processed, they can be collected, but they can't be processed! Can you tell me why, my console reports errors such as marijuana:
server / weed. Lua: 24: attempt to call a nil value (field'canswapitem ')
fn(@es_extended/server/functions.lua14)
My es_extended version is relatively new. I don't know if you are, but I hope it can be solved because I like this drug task very much.

**Comment by Xovos** [comment]
Hi,

I'm testing this on the latest verion of esx on my test server, works like a charm.
Did you try this verion: [https://github.com/Xovos/esx_illegal/tree/pre-limit-update](https://github.com/Xovos/esx_illegal/tree/pre-limit-update) ?
Try it and tell me if that fixed annything or made things worse.

Xovos
