### ISSUE TITLE
Super

### ISSUE THREAD

**Issue by rxbindotmp3** [Xovos/esx_illegal#16]
Hi man awsome script! Just wondering real quick, is there a way to not pick-up the drugs? Like can i some how enable it to be a circle or could you link me that script :)

**Comment by Xovos** [comment]
Hi
Could you clarify that a little, I don't understand the question.

**Comment by Demo4889** [comment]
@rxbindotmp3 means like the old ESX_Drugs where you just go to a location and hit a button to start harvesting or processing and have it keep going until you are done so someone doesn't have to walk from plant to plant, or keep hitting E to process each time.

**Comment by rxbindotmp3** [comment]
yea

**Comment by rxbindotmp3** [comment]
because there is no drug plugin working on my server not esx_drugs (any realeses) and not esx_illegal_drugs because the same problem happens every time when i try to collect. I can show you if you wan't to and or can help me :) It would be so appreciated.

**Comment by Demo4889** [comment]
if you want to show me, that is fine. I can either join your server, or you can take a video of it.

**Comment by rxbindotmp3** [comment]
I'll send some pictures wait about 5 mins. Thank you so much bro!

**Comment by rxbindotmp3** [comment]
Here, it's so sad because it works to pack & sell but not to collect. Any of them cocaine, weed, opium, meth :(
![1](https://user-images.githubusercontent.com/53920485/79626766-d7609380-8132-11ea-9bb4-c2592a112558.PNG)
![2](https://user-images.githubusercontent.com/53920485/79626770-dc254780-8132-11ea-8931-12b887dc3ed1.PNG)

The script i use: https://github.com/ESX-Org/esx_drugs/releases V1.0.2

**Comment by Demo4889** [comment]
That has nothing to do with this script... that is the original esx_drugs script, perhaps you should contact them on their issues board instead of here.

**Comment by rxbindotmp3** [comment]
I did now, thanks anyway 👍

**Comment by Demo4889** [comment]
what is line 53 anyway? im thinking i know how to do a quick fix considering they don't use limit anymore

**Comment by rxbindotmp3** [comment]
Shure ill send it

**Comment by rxbindotmp3** [comment]
![3](https://user-images.githubusercontent.com/53920485/79626847-cd8b6000-8133-11ea-8d72-a370fd609d3f.PNG)

**Comment by rxbindotmp3** [comment]
local function HarvestCoke(source)

	if CopsConnected < Config.RequiredCopsCoke then
		TriggerClientEvent('esx:showNotification', source, _U('act_imp_police', CopsConnected, Config.RequiredCopsCoke))
		return
	end

	SetTimeout(5000, function()

		if PlayersHarvestingCoke[source] == true then

			local xPlayer  = ESX.GetPlayerFromId(source)

			local coke = xPlayer.getInventoryItem('coke')

			if coke.limit ~= -1 and coke.count >= coke.limit then
				TriggerClientEvent('esx:showNotification', source, _U('inv_full_coke'))
			else
				xPlayer.addInventoryItem('coke', 1)
				HarvestCoke(source)
			end

		end
	end)
end

**Comment by rxbindotmp3** [comment]
That's where the error happens.

**Comment by Demo4889** [comment]
replace line 53 with

`if coke.limit == -1 and coke.count >= coke.limit then`

**Comment by rxbindotmp3** [comment]
ok tnx ill try

**Comment by rxbindotmp3** [comment]
OH MY FUCKING GOD DUDE FUCKING THANK YOU FOR FUCK SAKE

**Comment by rxbindotmp3** [comment]
You literally just saved my fucking server!

**Comment by rxbindotmp3** [comment]
Do you wan't loaf_housing i bought it?

**Comment by Demo4889** [comment]
They actually don't use "limit" anymore, so that version is old and not widely used anymore. es_extended has been updated and there are a lot of scripts you don't need anymore, so you should really think about updating a lot of things.

**Comment by Demo4889** [comment]
No idea what loaf_housing is, but i can take a look at it and see if it's something I could use.

**Comment by rxbindotmp3** [comment]
Damn, yeah i'll update sum. For example when my police search people's id the date says nil is that a quick fix?

**Comment by Demo4889** [comment]
If you wanna add me on discord, we can talk there so this doesn't keep getting comments on it. Demo#1180

**Comment by rxbindotmp3** [comment]
shure thanks bruv!

**Comment by Xovos** [comment]
@Demo4889 Thanks for the help in responding to the issues!
@rxbindotmp3 Hope this works out for you.
