### ISSUE TITLE
menu issues

### ISSUE THREAD

**Issue by Danny9865** [Xovos/esx_illegal#20]
before you open a menu, so when you're stood with the option to open a menu in the corner, the ms and ram usage goes through the roof. this is an issue if there's more than one person stood there. This is so high at the license area that i removed the license shop, but now i've noticed this is the same issue where you wash dirty money. when you open the menu the ms drops but just having the menu option where it says press E to open. that part goes crazy. Any chance you could take a look at this

**Comment by Xovos** [comment]
Hi

I have some questions to help me figure this out:
Does this only happin when you're not alone in the circle?
How much does it spike? 1gb 5gb? How much ram does your system have?
How do you mesure the ms? how much does it spike?

**Comment by Danny9865** [comment]
hi mate, i was using resmon  to see it, idle not close to it the cpu was sitting at around 0,04 ms but then as soon as one player walks into the radius for the menu it goes to 0.30 ms and for the memory its not that its high its that it climbs quick and doesnt stop climbing, within about 3 minutes it gives an es-extended resource warning. ram wise we run a 64gb dedicated server on OVH. it seems to climb at both the conversion point and the monewash location. but the most extreme was where you bought the licenses so for the time being ive got rid of that and put the licenses in a shop.
![image](https://user-images.githubusercontent.com/58650168/79856011-ab0f7600-83c3-11ea-8dd9-9b2eecb62ff5.png)
picture above was at money wash, seems to loop ok but it bounces quite high.

![image](https://user-images.githubusercontent.com/58650168/79856174-e5791300-83c3-11ea-804b-5ab1e759d20e.png)
picture above was at the chem conversion area. tbh looking at both of these they arent too bad they loop back down. Just the menu for the licenses that was too high

**Comment by Xovos** [comment]
Thank you For the answers I will look into it.
one more question are you running the latest (master) or the pre-limit-update version of the script?

**Comment by Danny9865** [comment]
![image](https://user-images.githubusercontent.com/58650168/79856719-9e3f5200-83c4-11ea-8360-ca2ce0a7d573.png)
that was putting the license shop back in btw

running the master mate as we're running esx 1.2 now

**Comment by Xovos** [comment]
Hi

I couldn't recreate the issue because i don't have anyone to test it with and my testserver is running on linux.
I did however clean up the code. I hope this resolves the problem a bit if not completely.

**Comment by Danny9865** [comment]
appreciate it mate, 

![image](https://user-images.githubusercontent.com/58650168/79904223-44627a80-840c-11ea-9d36-e65564efb973.png)
noticed this gets spammed when they pick up drugs from certain plants, im not 100% sure which ones yet. just wandered if you knew much about it

**Comment by Xovos** [comment]
Hi

I did get that once, but I can't get it to come up again though.
Google tells me it has something to do with a full inventory but I don't know, I didn't even change anything from the pickup code.

**Comment by Danny9865** [comment]
![image](https://user-images.githubusercontent.com/58650168/79932103-9f17c880-8444-11ea-993d-4c4318923114.png)
god knows its on a mad one lol, doesn't actually seem to affect anything, looks ugly console side, il do some digging

**Comment by Danny9865** [comment]
any way to make it so cops have to be online to do the drugs?

**Comment by Xovos** [comment]
Hi

If you find something contact me please.
The Latest version of the script contains the option for the cops.
Did my changes, fix the ram and ms issue?
If you don't like to communicate this way you can add me on discord that's always easier.
Xovos#7610
