### ISSUE TITLE
Line 56 server/main.lua

### ISSUE THREAD

**Issue by RandomZFx** [Xovos/esx_illegal#21]
Typo I am assuming. canCarry is not a statement for pre-limit.  I changed it to 	cb(xPlayer.getInventoryItem(item, 1)) and it works just fine now :)

**Comment by Xovos** [comment]
Hi
Thanks for pointing that out, Indeed, that isn't supposed to be there. It slipped past me when I updated the code to the newer version. I pushed a fix thanks.
