### ISSUE TITLE
No collecting possible

### ISSUE THREAD

**Issue by 1UniQueGirl1** [Xovos/esx_illegal#22]
After I installed everything, everything was displayed to me. Unfortunately, harvesting is not possible. The message "Press (Button) ..." appears, but nothing happens afterwards. Why is that?

**Comment by Xovos** [comment]
Hi

Could you give me some more info to work with like a screenshot from the server console or from the client console "F8" maybe a small video where you do this that shows what happens?

**Comment by 1UniQueGirl1** [comment]
There is no error message. If the player wants to harvest, he does not bend over to harvest. Nothing happens

**Comment by Xovos** [comment]
Hi

Strange, Do you have "RequireCopsOnline" Enabled in the config and are their enough cops online?
Are you getting this message: "You cannot participate illegal activities unless there\'s enough cops online."?

**Comment by 1UniQueGirl1** [comment]
Config.RequireCopsOnline = false

Config.Cops = {
	Heroin = 0,
	Weed = 0,
	Coke = 0,
	Meth = 0,
	LSD = 0,
	Chemicals = 0,
	MoneyWash = 0,
	ChemicalsMenu = 0,
	DrugDealer = 0,
	LicenseShop = 0,

I dont get this message

**Comment by Xovos** [comment]
Hi

Are you running into this problem with a specific pickup or is this the same for every pickup?
Are you able to process? Try giving yourself some items that you would get from the pickup and try to process it.

**Comment by 1UniQueGirl1** [comment]
all processes don't work

**Comment by Xovos** [comment]
Hi

Any error messages?
Did you add the items to the database: Rand the sql Script?
I think you will have more luck with this version: [https://github.com/Xovos/esx_illegal/tree/pre-limit-update](https://github.com/Xovos/esx_illegal/tree/pre-limit-update)

**Comment by 1UniQueGirl1** [comment]
No error messages. I try it with esx_drugs. Everything works there. Unfortunately not with your script

**Comment by Xovos** [comment]
Hi

Please try this version of the script and tell me if that fixed annything, you will have to remove all the items from the script from the database and re-add them.
[https://github.com/Xovos/esx_illegal/tree/pre-limit-update](https://github.com/Xovos/esx_illegal/tree/pre-limit-update)

**Comment by 1UniQueGirl1** [comment]
Its working now. Thank you so much

**Comment by Xovos** [comment]
Happy to help
