### ISSUE TITLE
Cant harvest DRUGS

### ISSUE THREAD

**Issue by BelgiumRP** [Xovos/esx_illegal#24]
The moment i press e on the location/barrels  its not doing the animation  and after i pressed e once i cant do this anymore do you have any fix for this issue?

**Comment by Xovos** [comment]
Hi

Yes, please use this version of the script: https://github.com/Xovos/esx_illegal/tree/pre-limit-update

**Comment by BelgiumRP** [comment]
Hey, Works fine now  thank you have a nice evening
