### ISSUE TITLE
Enable contant process

### ISSUE THREAD

**Issue by AlucardVoss** [Xovos/esx_illegal#25]
Is it possible to add an config option where process is automatic instead of just Pressing E every time ?

**Comment by Xovos** [comment]
Hi

Yes, but this would require some rewriting and I currently don't have the time sorry.

**Comment by AlucardVoss** [comment]
No no it's ok, was just wondering anyway, gonna try to re-write it if its OK with you

**Comment by Xovos** [comment]
Yes, no problem

If you find out how and want to share it with the community you can always contribute, just make a pull request.

**Comment by AlucardVoss** [comment]
Heck yes =]
