### ISSUE TITLE
swapitem

### ISSUE THREAD

**Issue by FiveM-DEV** [Xovos/esx_illegal#26]
this is my problem https://prnt.sc/sctinx

**Comment by Xovos** [comment]
Hi

Please use this version of the script: https://github.com/Xovos/esx_illegal/tree/pre-limit-update

**Comment by FiveM-DEV** [comment]
dosnt work next error
https://prnt.sc/sd6m9t

**Comment by Xovos** [comment]
Hi

Good news: You're not alone: [https://github.com/Xovos/esx_illegal/issues/23](https://github.com/Xovos/esx_illegal/issues/23)

Bad news: I haven't found the solution to this very rare bug yet.

I think your version of esx is incompatible.

**Comment by FiveM-DEV** [comment]
can you update the script pls

**Comment by Xovos** [comment]
Could you tell me which version of esx you are using?

**Comment by miraz559** [comment]
can you make it for esx version 1.1.0 because maximum users use this version if you can find a fix it would be helpfull

**Comment by Xovos** [comment]
Hi

This version: [https://github.com/Xovos/esx_illegal/tree/pre-limit-update](https://github.com/Xovos/esx_illegal/tree/pre-limit-update)
Is made for 1.1.0 and it works like a charm on my 1.1.0 Test server.

**Comment by miraz559** [comment]
i am using this one but doesn't work if someones picks anything it doesn't process

**Comment by Xovos** [comment]
I don't really understand what you mean by that sentence.
Did you remove the items from the master branch from the database and re-add the ones from this one?

**Comment by miraz559** [comment]
if i try to process the domain it doesn't process it picks but doesn't process

**Comment by Xovos** [comment]
Did you remove the items from the master branch from the database and re-add the ones from this one?

**Comment by miraz559** [comment]
i tried everything i talked with you about it before and i also created a demo server also for this the result is same

**Comment by Xovos** [comment]
This is my problem: First you got the error "swapitem" not found which is a clear indication that you are not running V1.2.0 then when you switched to the V1.1.0 version you get the error null at the limit in the script which is a clear indication that you are running v1.2.0 so this doesn't make sense.

Could you give me a screenshot of the contents of your "Items" Table in your database?

**Comment by miraz559** [comment]
i will newly install everything and let you know what happens i will send you screenshots

**Comment by Xovos** [comment]
Oh okay, thanks, Keep me updated.

**Comment by miraz559** [comment]
ok it works now when i have input the esx org es_extended it works so smooth but it doesn't work on esx brazil version and the latest version esx also does not work and i saw many more scripts i didn't get them how can i get them

**Comment by Xovos** [comment]
Hi

Great, progress has been made! es_extended is "ESX", it's a dependency for this script and you if you want to use the latest versions of es_extended v1.2.0 then you will need the master branch of this script. The other scripts are probably not supported by this new version of es_extended so you would have to update these too.
