### ISSUE TITLE
issues with collect drug

### ISSUE THREAD

**Issue by tieumieu90** [Xovos/esx_illegal#29]
when I hit E and it didn't do anything

**Comment by Xovos** [comment]
Hi

Please check out this issue, it has the answer to your problem.
[https://github.com/Xovos/esx_illegal/issues/22](https://github.com/Xovos/esx_illegal/issues/22)

**Comment by tieumieu90** [comment]
it can't college the chemicals, 
Sh and SA = no place to college it

**Comment by tieumieu90** [comment]
I can't collect the chemical

**Comment by tieumieu90** [comment]
it shows the action but it n't receive the chemical but it on in my inventory

**Comment by Xovos** [comment]
Please tell me the version of ESX you are running.

**Comment by tieumieu90** [comment]
https://github.com/Xovos/esx_illegal/tree/pre-limit-update 
this version

**Comment by tieumieu90** [comment]
can you join my discord to check for us
https://discord.gg/GmejxU

**Comment by Xovos** [comment]
I joined you can see me as Xovos#7610

**Comment by tieumieu90** [comment]
join any sever i will move you

**Comment by tieumieu90** [comment]
join sever I will move you to talk with us

**Comment by NEIDER12** [comment]
> join sever I will move you to talk with us

Have this issue too! How do we fix it?

**Comment by Xovos** [comment]
The issue we have here is that the chemicals can't be picked up all the other drugs can. If you can't pick up let's say weed then you're probably on the wrong branche.
