### ISSUE TITLE
No Marker for Doors 

### ISSUE THREAD

**Issue by vichuvrn** [Xovos/esx_illegal#3]
No marker for doors to enter weed processing , Meth processing area

**Comment by Xovos** [comment]
These are nog included, you can change the location or install a teleport and a interior addon.

**Comment by Xovos** [comment]
Here's a teleportation script for the locations:
https://github.com/Xovos/XOVOS_Teleport

**Comment by vichuvrn** [comment]
Thank you so much bro :)

**Comment by vichuvrn** [comment]
@Xovos  can you do me a favor.. can you please delete issue #3 and #4 which i created
