### ISSUE TITLE
Can't load .sql in data base.

### ISSUE THREAD

**Issue by sergio03spm** [Xovos/esx_illegal#30]
Whenever I try ro upload the sql it gives me this error.
![image](https://user-images.githubusercontent.com/67983987/86852558-4bb52e00-c0b5-11ea-8559-95aebde7fb83.png)
Help pls!

**Comment by Xovos** [comment]
Hi
please use this version of the script
[https://github.com/Xovos/esx_illegal/tree/pre-limit-update](https://github.com/Xovos/esx_illegal/tree/pre-limit-update)

**Comment by sergio03spm** [comment]
> Hi
> please use this version of the script
> https://github.com/Xovos/esx_illegal/tree/pre-limit-update

i'm using this version

**Comment by Xovos** [comment]
No you are not, the pre-limit-update sql does not have "weight"

**Comment by sergio03spm** [comment]
![image](https://user-images.githubusercontent.com/67983987/86855070-ef084200-c0b9-11ea-9f30-a1d9c0b5e90e.png)
Another problem, wtf

**Comment by sergio03spm** [comment]
> No you are not, the pre-limit-update sql does not have "weight"

i dont understand

**Comment by Xovos** [comment]
the last image tell's me that "cannabis" is already added to the database

**Comment by sergio03spm** [comment]
how do i delete it?

**Comment by Xovos** [comment]
but don't you want it to be in the database?

**Comment by sergio03spm** [comment]
sure, but is it the same file than the one i alredy have in the database?

**Comment by Xovos** [comment]
uh you tell me check in the database if the items are all there
