### ISSUE TITLE
sql for esx v1.2

### ISSUE THREAD

**Issue by DamjanPetrovicki** [Xovos/esx_illegal#31]
Why is there USE `essentialmode`; in version for esx 1.2 (USE `es_extended`)

**Comment by DamjanPetrovicki** [comment]
I want to make a pr but i cant rn, so if you can change that

**Comment by Xovos** [comment]
Hi

Thanks for letting me know, I just pushed it to the master branch.

Xovos

**Comment by synceye** [comment]
Thank you! (love ur work btw <3)
