### ISSUE TITLE
No issue , just a question

### ISSUE THREAD

**Issue by Maureks** [Xovos/esx_illegal#38]
How can I change the amount , for exemple : for every berrel I only get 1 item of the specified drug , what can I do to make it a bigger amount ?

If it's possible 

The whole script works like a charm, no problem at all 

Much thanks in advance

**Comment by Xovos** [comment]
Hi

yes this is possible, you will just need to go into the server file of the drug you want to change and change the number in the function.

![image](https://user-images.githubusercontent.com/13740700/123521127-023e6400-d6b5-11eb-9889-002232ceccd7.png)
here is an example for the chemicals

Xovos

**Comment by Maureks** [comment]
Much much much thanks !
