### ISSUE TITLE
possible to sell on streets?

### ISSUE THREAD

**Issue by OwnageGalore** [Xovos/esx_illegal#6]
the old drug script i had esx_drugs i linked with stasiek_selldrugs - players could then sell the drugs on the streets to locals, is it possible with this?

**Comment by Xovos** [comment]
It looks like that script was made for the old version of esx_drugs as you said, the new one is completely different with you picking up the plants and everything. This script is based on the new one so it will not work.

**Comment by OwnageGalore** [comment]
possible to code it in? or do i need another sell script i know ive seen one someplace, srry i only have a few months experience doing all of this.

**Comment by Xovos** [comment]
I'm positive that i can change that script so that it works with this one but i don't have the time at the moment sorry.
