### ISSUE TITLE
How to fix this

### ISSUE THREAD

**Issue by Taker54** [Xovos/esx_illegal#7]
This is my error, how to fix this.

SCRIPT ERROR: @esx_society/server/main.lua:334: attempt to index a nil value (local 'store')
> ref (@esx_society/server/main.lua:334)
> handler (@esx_datastore/server/main.lua:80)
> ref (@esx_society/server/main.lua:333)
> TriggerServerCallback (@es_extended/server/functions.lua:33)
> handler (@es_extended/server/common.lua:88)

**Comment by Xovos** [comment]
Unrelated.
