### ISSUE TITLE
When processing LSA Error happens then shortly after menu disappears

### ISSUE THREAD

**Issue by taysupra** [Xovos/esx_illegal#8]
InvokeNative: execution failed: Argument at index 1 was null.
SCRIPT ERROR: Execution of native 000000002f7a49e6 in script host failed

Is the error spammed in console when the menu is being used. 
If needed i can add more data for what you want. But as it is. it's a standard most up to date version of esx_illegal.

Thank you!

**Comment by Xovos** [comment]
I'm sorry but i'm not expirianced enough to even try to understand what this error means.
I know the basics of coding but nothing fivem specific so i had the expiriance to make this script but not to know this.
